export interface ModuleDefinition {
  typeId: number;
  name: string;
  category: string;
}

export const MODULE_DEFINITIONS: Record<number, ModuleDefinition> = {
  0: { typeId: 0, name: "SV Filter", category: "Audio" },
  1: { typeId: 1, name: "Audio Input", category: "Interface" },
  2: { typeId: 2, name: "Audio Output", category: "Interface" },
  3: { typeId: 3, name: "Aliaser", category: "Audio" },
  4: { typeId: 4, name: "Sequencer", category: "Control" },
  5: { typeId: 5, name: "LFO", category: "Control" },
  6: { typeId: 6, name: "ADSR", category: "Control" },
  7: { typeId: 7, name: "VCA", category: "Audio" },
  8: { typeId: 8, name: "Audio Multiply", category: "Audio" },
  9: { typeId: 9, name: "Bit Crusher", category: "Audio" },
  10: { typeId: 10, name: "Sample & Hold", category: "Control" },
  11: { typeId: 11, name: "OD & Distortion", category: "Effect" },
  12: { typeId: 12, name: "Env Follower", category: "Analysis" },
  13: { typeId: 13, name: "Delay Line", category: "Audio" },
  14: { typeId: 14, name: "Oscillator", category: "Audio" },
  15: { typeId: 15, name: "Pushbutton", category: "Interface" },
  16: { typeId: 16, name: "Keyboard", category: "Interface" },
  17: { typeId: 17, name: "CV Invert", category: "Control" },
  18: { typeId: 18, name: "Steps", category: "Control" },
  19: { typeId: 19, name: "Slew Limiter", category: "Control" },
  20: { typeId: 20, name: "MIDI Notes in", category: "Interface" },
  21: { typeId: 21, name: "MIDI CC in", category: "Interface" },
  22: { typeId: 22, name: "Multiplier", category: "Control" },
  23: { typeId: 23, name: "Compressor", category: "Effect" },
  24: { typeId: 24, name: "Multi-Filter", category: "Audio" },
  25: { typeId: 25, name: "Plate Reverb", category: "Effect" },
  26: { typeId: 26, name: "Buffer Delay", category: "Audio" },
  27: { typeId: 27, name: "All-Pass Filter", category: "Audio" },
  28: { typeId: 28, name: "Quantizer", category: "Control" },
  29: { typeId: 29, name: "Phaser", category: "Effect" },
  30: { typeId: 30, name: "Looper", category: "Audio" },
  31: { typeId: 31, name: "In Switch", category: "Control" },
  32: { typeId: 32, name: "Out Switch", category: "Control" },
  33: { typeId: 33, name: "Audio In Switch", category: "Audio" },
  34: { typeId: 34, name: "Audio Out Switch", category: "Audio" },
  35: { typeId: 35, name: "Midi Pressure", category: "Interface" },
  36: { typeId: 36, name: "Onset Detector", category: "Analysis" },
  37: { typeId: 37, name: "Rhythm", category: "Control" },
  38: { typeId: 38, name: "Noise", category: "Audio" },
  39: { typeId: 39, name: "Random", category: "Control" },
  40: { typeId: 40, name: "Gate", category: "Effect" },
  41: { typeId: 41, name: "Tremolo", category: "Effect" },
  42: { typeId: 42, name: "Tone Control", category: "Effect" },
  43: { typeId: 43, name: "Delay w/Mod", category: "Effect" },
  44: { typeId: 44, name: "Stompswitch", category: "Interface" },
  45: { typeId: 45, name: "Value", category: "Control" },
  46: { typeId: 46, name: "CV Delay", category: "Control" },
  47: { typeId: 47, name: "CV Loop", category: "Control" },
  48: { typeId: 48, name: "CV Filter", category: "Control" },
  49: { typeId: 49, name: "Clock Divider", category: "Control" },
  50: { typeId: 50, name: "Comparator", category: "Control" },
  51: { typeId: 51, name: "CV Rectify", category: "Control" },
  52: { typeId: 52, name: "Trigger", category: "Control" },
  53: { typeId: 53, name: "Stereo Spread", category: "Audio" },
  54: { typeId: 54, name: "Cport Exp/CV in", category: "Interface" },
  55: { typeId: 55, name: "Cport CV out", category: "Interface" },
  56: { typeId: 56, name: "UI Button", category: "Interface" },
  57: { typeId: 57, name: "Audio Panner", category: "Audio" },
  58: { typeId: 58, name: "Pitch Detector", category: "Analysis" },
  59: { typeId: 59, name: "Pitch Shifter", category: "Audio" },
  60: { typeId: 60, name: "Midi Note Out", category: "Interface" },
  61: { typeId: 61, name: "Midi CC Out", category: "Interface" },
  62: { typeId: 62, name: "Midi PC Out", category: "Interface" },
  63: { typeId: 63, name: "Bit Modulator", category: "Audio" },
  64: { typeId: 64, name: "Audio Balance", category: "Audio" },
  65: { typeId: 65, name: "Inverter", category: "Audio" },
  66: { typeId: 66, name: "Fuzz", category: "Effect" },
  67: { typeId: 67, name: "Ghostverb", category: "Effect" },
  68: { typeId: 68, name: "Cabinet Sim", category: "Effect" },
  69: { typeId: 69, name: "Flanger", category: "Effect" },
  70: { typeId: 70, name: "Chorus", category: "Effect" },
  71: { typeId: 71, name: "Vibrato", category: "Effect" },
  72: { typeId: 72, name: "Env Filter", category: "Effect" },
  73: { typeId: 73, name: "Ring Modulator", category: "Effect" },
  74: { typeId: 74, name: "Hall Reverb", category: "Effect" },
  75: { typeId: 75, name: "Ping Pong Delay", category: "Effect" },
  76: { typeId: 76, name: "Audio Mixer", category: "Audio" },
  77: { typeId: 77, name: "CV Flip Flop", category: "Control" },
  78: { typeId: 78, name: "Diffuser", category: "Audio" },
  79: { typeId: 79, name: "Reverb Lite", category: "Effect" },
  80: { typeId: 80, name: "Room Reverb", category: "Effect" },
  81: { typeId: 81, name: "Pixel", category: "Interface" },
  82: { typeId: 82, name: "Midi Clock In", category: "Interface" },
  83: { typeId: 83, name: "Granular", category: "Audio" },
  84: { typeId: 84, name: "Midi Clock Out", category: "Interface" },
  85: { typeId: 85, name: "Tap to CV", category: "Control" },
  86: { typeId: 86, name: "MIDI Pitch Bend In", category: "Interface" },
  103: { typeId: 103, name: "Device Control", category: "Interface" },
  104: { typeId: 104, name: "CV Mixer", category: "Control" },
};

export function getModuleDefinition(typeId: number): ModuleDefinition | undefined {
  return MODULE_DEFINITIONS[typeId];
}
